spring:
  profiles:
    active: test

  datasource:
    datasource:
      url: jdbc:h2:file:./target/recipe;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      username: sa
      password:
      driverClassName: org.h2.Driver
      hikari:
        minimumIdle: 2
        maximumPoolSize: 100
        idleTimeout: 30000
        maxLifetime: 2000000
        connectionTimeout: 30000
    data:
      - classpath:initial_load_data.sql

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      properties:
        format-sql: false

  liquibase:
    change-log: classpath:db/changelog-master/db.changelog-master.xml
