--liquibase formatted sql

--changeset AndreFelipeCL92:001.01
INSERT INTO CATEGORY (ID, CATEGORY_NAME)
VALUES (NEXTVAL('CATEGORY_ID_SEQ'), 'American'),
       (NEXTVAL('CATEGORY_ID_SEQ'), 'Italian'),
       (NEXTVAL('CATEGORY_ID_SEQ'), 'Mexican'),
       (NEXTVAL('CATEGORY_ID_SEQ'), 'Fast Food'),
       (NEXTVAL('CATEGORY_ID_SEQ'), 'Brazilian');
--rollback DELETE FROM CATEGORY WHERE CATEGORY_NAME = 'American';
--rollback DELETE FROM CATEGORY WHERE CATEGORY_NAME = 'Italian';
--rollback DELETE FROM CATEGORY WHERE CATEGORY_NAME = 'Mexican';
--rollback DELETE FROM CATEGORY WHERE CATEGORY_NAME = 'Fast Food';
--rollback DELETE FROM CATEGORY WHERE CATEGORY_NAME = 'Brazilian';

--changeset AndreFelipeCL92:001.02
INSERT INTO UNIT_OF_MEASURE (ID, DESCRIPTION)
VALUES (NEXTVAL('UNIT_OF_MEASURE_ID_SEQ'), 'Teaspoon'),
       (NEXTVAL('UNIT_OF_MEASURE_ID_SEQ'), 'Tablespoon'),
       (NEXTVAL('UNIT_OF_MEASURE_ID_SEQ'), 'Cup'),
       (NEXTVAL('UNIT_OF_MEASURE_ID_SEQ'), 'Pinch'),
       (NEXTVAL('UNIT_OF_MEASURE_ID_SEQ'), 'Ounce');
--rollback DELETE FROM UNIT_OF_MEASURE WHERE DESCRIPTION = 'Teaspoon';
--rollback DELETE FROM UNIT_OF_MEASURE WHERE DESCRIPTION = 'Tablespoon';
--rollback DELETE FROM UNIT_OF_MEASURE WHERE DESCRIPTION = 'Cup';
--rollback DELETE FROM UNIT_OF_MEASURE WHERE DESCRIPTION = 'Pinch';
--rollback DELETE FROM UNIT_OF_MEASURE WHERE DESCRIPTION = 'Ounce';